import { Geist, Geist_Mono } from "next/font/google";
import { Footer } from "@/components/common/footer/footer";

export const metadata = {
  title: "CinemaIsLove",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
