import { Geist, Geist_Mono } from "next/font/google";


export const metadata = {
  title: "CinemaIsLove",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
